### PR TITLE
🐞 fix: NPE crash problem

### PR DESCRIPTION
**Pull request by Leobuaa**
https://github.com/leanflutter/clipboard_watcher/issues/13

### CODE REVIEW

**Comment by Leobuaa** [comment]
@jpnurmi @ademar111190 @boparaiamritcsb Hello~

**Comment by ademar111190** [comment]
I don't have permission on this repo to merge your fix @Leobuaa 
Try adding the owner of the repo as a reviewer

**Comment by Leobuaa** [comment]
> write access

OK

**Comment by Leobuaa** [comment]
@lijy91 Hello, can you review my code and merge.

**Pull request merged**
